# Configuration for the generator.
# See documentation for keys inside pkg/config/config.go
hostname: go.nc0.fr
modules:
  # https://go.nc0.fr/foo -> https://github.com/n1c00o/foo-go
  - prefix: foo
    dir: "https://github.com/n1c00o/foo-go/tree/master{/dir}"
    file: "https://github.com/n1c00o/foo-go/blob/master{/dir}/{file}#L{line}"
    repo: "https://github.com/n1c00o/foo-go.git"
    vcs: git
  # https://go.nc0.fr/rozoe -> https://github.com/n1c00o/rozoe
  - prefix: rozoe
    dir: "https://github.com/n1c00o/rozoe/tree/master{/dir}"
    file: "https://github.com/n1c00o/rozoe/blob/master{/dir}/{file}#L{line}"
    repo: "https://github.com/n1c00o/rozoe.git"
    vcs: git
  # https://go.nc0.fr/feur_bot -> https://github.com/n1c00o/feur_bot
  - prefix: feur_bot
    dir: "https://github.com/n1c00o/feur_bot/tree/master{/dir}"
    file: "https://github.com/n1c00o/feur_bot/blob/master{/dir}/{file}#L{line}"
    repo: "https://github.com/n1c00o/feur_bot.git"
    vcs: git
  # https://go.nc0.fr/clawflake -> https://github.com/n1c00o/clawflake
  - prefix: clawflake
    dir: "https://github.com/n1c00o/clawflake/tree/master{/dir}"
    file: "https://github.com/n1c00o/clawflake/blob/master{/dir}/{file}#L{line}"
    repo: "https://github.com/n1c00o/clawflake.git"
    vcs: git
  # https://go.nc0.fr/github-random -> https://github.com/n1c00o/github-random
  - prefix: github-random
    dir: "https://github.com/n1c00o/github-random/tree/master{/dir}"
    file: "https://github.com/n1c00o/github-random/blob/master{/dir}/{file}#L{line}"
    repo: "https://github.com/n1c00o/github-random.git"
    vcs: git
